---
- name: Deploy application
  hosts: app
  tasks:
  - name: Fetch the lastest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit
    notify: restart puma
  handlers:
  - name: restart puma
    become: true
    systemd:
      name: puma
      state: restarted
...
