name: Run Packer templates validation

on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # # fix backwards incompatibilities in template
      # - name: Fix Template
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: fix

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ./packer
        env:
          PACKER_LOG: 1
