name: Run Terraform configs validation

on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environenment: ["stage", "prod"]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      id: init
      run: terraform init ./terraform/{{ matrix.environenment }}
      working

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color ./terraform/{{ matrix.environenment }}
